import { format, parseISO } from "date-fns"
import { AlertTriangle, Clock, LayoutGrid, Lightbulb, TrendingUp } from "lucide-react"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { useInsights } from "@/hooks/useInsights"
import type { InsightItem, InsightSeverity, InsightType } from "@/lib/types"
import { cn } from "@/lib/utils"

interface InsightsPanelProps {
  dateFrom: string
  dateTo: string
  isSyncing: boolean
}

const TYPE_ICON: Record<InsightType, typeof TrendingUp> = {
  pattern: TrendingUp,
  anomaly: AlertTriangle,
  saving: Lightbulb,
  rhythm: Clock,
  category: LayoutGrid,
}

const SEVERITY_BORDER: Record<InsightSeverity, string> = {
  info: "border-l-primary",
  warning: "border-l-warning",
  positive: "border-l-success",
}

function providerLabel(provider: string | null) {
  if (!provider) return null
  return provider.charAt(0).toUpperCase() + provider.slice(1)
}

export function InsightsPanel({ dateFrom, dateTo, isSyncing }: InsightsPanelProps) {
  const { data } = useInsights(dateFrom, dateTo)

  const insights = data?.insights ?? []
  const provider = providerLabel(data?.provider ?? null)
  const generatedAtLabel = data?.generatedAt ? format(parseISO(data.generatedAt), "d MMM yyyy") : null

  const isEmpty = !isSyncing && insights.length === 0

  return (
    <Card className="mt-6">
      <CardHeader>
        <CardTitle className="text-base font-semibold text-text-primary">AI Insights</CardTitle>
        {/* Only claims a generation happened when there's something to show for
            it — the job still reports its own provider/timestamp even on a run
            where insight generation itself failed (e.g. a transient 503 from
            the LLM), which would otherwise read as "Generated by Gemini" right
            above a "Could not generate insights right now" message. */}
        {provider && generatedAtLabel && !isSyncing && !isEmpty && (
          <p className="text-sm text-text-secondary">
            Generated by {provider} · {generatedAtLabel}
          </p>
        )}
      </CardHeader>
      <CardContent>
        {isSyncing ? (
          <div className="grid grid-cols-2 gap-4">
            {Array.from({ length: 5 }).map((_, i) => (
              <Skeleton key={i} className={cn("h-28", i === 4 && "col-span-2")} />
            ))}
          </div>
        ) : isEmpty ? (
          <div className="flex min-h-[112px] items-center justify-center text-sm text-text-secondary">
            {data?.errorMessage ?? "Run a sync to generate insights"}
          </div>
        ) : (
          <div className="grid grid-cols-2 gap-4">
            {insights.map((insight, i) => (
              <InsightCard
                key={`${insight.type}-${i}`}
                insight={insight}
                provider={provider}
                className={i === insights.length - 1 && insights.length % 2 === 1 ? "col-span-2" : undefined}
              />
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  )
}

function InsightCard({
  insight,
  provider,
  className,
}: {
  insight: InsightItem
  provider: string | null
  className?: string
}) {
  const Icon = TYPE_ICON[insight.type]

  return (
    <div
      className={cn(
        "relative flex flex-col gap-2 rounded-lg border border-border border-l-4 bg-card p-4",
        SEVERITY_BORDER[insight.severity],
        className
      )}
    >
      <div className="flex items-start gap-2.5">
        <Icon className="mt-0.5 size-4 shrink-0 text-text-secondary" />
        <h3 className="text-sm font-semibold text-text-primary">{insight.title}</h3>
      </div>
      <p className="text-sm text-text-secondary">{insight.body}</p>
      {provider && (
        <span className="absolute right-3 bottom-3 rounded-full bg-muted px-2 py-0.5 text-[11px] font-medium text-text-secondary">
          {provider}
        </span>
      )}
    </div>
  )
}
