"""Temporary local HTTPS server that catches Enable Banking's OAuth redirect
automatically (S3-07 Item 2) — replaces S2-02's copy-paste-the-URL flow.

Listens on CALLBACK_PORT for exactly one request, then shuts itself down.
Runs in the celery_worker process (see tasks/auth.py), never in the FastAPI
process — waiting for a browser redirect can take minutes, and blocking a
worker process is exactly what the whole Celery setup (S3-03/S3-04) exists to
allow, unlike blocking an API request.

Serves HTTPS, not HTTP: the Enable Banking developer portal only accepts
https:// scheme redirect URIs, so the earlier http://localhost:3001/callback
build was rejected outright with "Redirect URI not allowed". The cert/key
here are generated by mkcert (a local trusted CA for dev), not a real CA —
fine for a redirect target that only ever receives one request from a
browser the developer themselves just opened.
"""
import logging
import ssl
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

logger = logging.getLogger(__name__)

CALLBACK_PORT = 3001

_CERTS_DIR = Path(__file__).resolve().parent.parent / "certs"
CERT_FILE = _CERTS_DIR / "localhost.pem"
KEY_FILE = _CERTS_DIR / "localhost-key.pem"

# This is a plain http.server response with no access to the frontend's
# index.css or React components, so the brand's colors and font are inlined
# by hand rather than imported — kept in sync manually with the design
# tokens (#2563EB primary, #16A34A success) rather than shared automatically.
_CONFIRMATION_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>KBC Analyzer</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: "Inter", -apple-system, BlinkMacSystemFont, sans-serif;
    background: #F8FAFC;
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    color: #1E293B;
  }
  .card {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    gap: 16px;
    padding: 48px 40px;
  }
  .wordmark {
    font-size: 15px;
    font-weight: 700;
    letter-spacing: 0.02em;
    color: #2563EB;
    margin-bottom: 8px;
  }
  .icon {
    width: 64px;
    height: 64px;
    border-radius: 999px;
    background: #DCFCE7;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  h1 {
    font-size: 22px;
    font-weight: 600;
    color: #0F172A;
  }
  p {
    font-size: 15px;
    color: #64748B;
  }
</style>
</head>
<body>
  <div class="card">
    <div class="wordmark">KBC Analyzer</div>
    <div class="icon">
      <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="#16A34A" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
        <path d="M20 6L9 17l-5-5"/>
      </svg>
    </div>
    <h1>Bank connected successfully</h1>
    <p>You can close this tab and return to the app</p>
  </div>
</body>
</html>"""


class _CallbackHandler(BaseHTTPRequestHandler):
    def do_GET(self) -> None:
        params = parse_qs(urlparse(self.path).query)
        # Stashed on the server instance (not a class attribute) so a second,
        # unrelated reconnect attempt's server can never read another one's
        # result — see wait_for_callback(), which creates one handler class
        # per call specifically to keep this isolated.
        self.server.callback_result = {  # type: ignore[attr-defined]
            "code": params.get("code", [None])[0],
            "state": params.get("state", [None])[0],
        }
        self.send_response(200)
        self.send_header("Content-Type", "text/html")
        self.end_headers()
        self.wfile.write(_CONFIRMATION_PAGE.encode("utf-8"))

    def log_message(self, format: str, *args) -> None:  # noqa: A002 - matches base signature
        pass  # BaseHTTPRequestHandler logs every request to stderr by default; too noisy here


class CallbackPortBusyError(Exception):
    """Another reconnect attempt's server is still bound to CALLBACK_PORT —
    confirmed live: refreshing the page mid-reconnect and clicking Reconnect
    again fires a second task while the first is still waiting (up to its
    full timeout), and the second one's bind() fails with "Address already
    in use" if not caught here."""


def wait_for_callback(timeout_seconds: int = 300) -> dict:
    """Starts a local server on CALLBACK_PORT, blocks until Enable Banking's
    redirect hits it (or timeout_seconds elapses), then shuts down.

    Raises TimeoutError if nothing arrives in time, CallbackPortBusyError if
    another attempt already owns the port. Returns {"code": str|None,
    "state": str|None} otherwise — callers still need to check code is present,
    since a malformed redirect could hit this with no code at all.
    """
    try:
        server = HTTPServer(("0.0.0.0", CALLBACK_PORT), _CallbackHandler)
    except OSError as exc:
        raise CallbackPortBusyError(
            f"Port {CALLBACK_PORT} is already in use by another reconnect attempt."
        ) from exc

    ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ssl_context.load_cert_chain(certfile=str(CERT_FILE), keyfile=str(KEY_FILE))
    server.socket = ssl_context.wrap_socket(server.socket, server_side=True)

    server.callback_result = None  # type: ignore[attr-defined]
    server.timeout = timeout_seconds

    server.handle_request()  # blocks for exactly one request, or until timeout
    server.server_close()

    result = getattr(server, "callback_result", None)
    if result is None:
        raise TimeoutError(f"No authorization callback received within {timeout_seconds} seconds.")
    return result
